### ISSUE TITLE
Only bug id should be given as input (removal of project arg).

### ISSUE THREAD

**Issue by fermadeiral** [tdurieux/patch-clustering#1]
Currently, `bug id` and `project` are required as input. This is possible because the way Defects4J is organized. However, to extract features from patches from other bug datasets it might not be possible.

**Comment by victor-sobreira** [comment]
Can you explain better about this issue Fernanda? I suppose this kind of meta info does not influence on feature processing. It's a way to identify the bugs in a dataset and I think we should adapt to the reality of each one. For Defects4J, the bug identification depends on the project (not only the numerical part), so it is a requirement to have this kind of composite key for their bugs.

**Comment by fermadeiral** [comment]
> I suppose this kind of meta info does not influence on feature processing.

Correct. They are only used to print info.

> For Defects4J, the bug identification depends on the project (not only the numerical part) [...]

I understand your concern, thus I will try to clarify what I meant. Currently, to run the java program to extract features, it is required (!) to give value for the arguments `project` and `bug id`. To run the java program on Defects4J bugs, then, we pass something like this: `project=Chart` and `bug id=1`. See that when we refer to this bug, we say "Chart 1". Even in the Defects4J dissection website we put in the column "Bug id" like "Chart 1". I understand your concern because I think you thought I want to completely ignored the project name, but in fact I want to have a single argument `bug id` where we would enter with "Chart 1". It doesn't affect the functionality of the extractor, but simplifies its usage (the more arguments, the more difficult to use and also to maintain the code).
