### ISSUE TITLE
Release ADD

### ISSUE THREAD

**Issue by fermadeiral** [tdurieux/patch-clustering#12]
Hi boys. What about releasing the project so we can keep track on the version of the project that was used in the VEM'18 paper? Would that be version 1.0?

**Comment by maiamarcelo** [comment]
Agreed.
[]s
Marcelo
UFU-FACOM

**Comment by fermadeiral** [comment]
First release done: https://github.com/lascam-UFU/automatic-diff-dissection/releases/tag/v1.0
